source 'https://rubygems.org'
gem 'telegram-bot-ruby'
gem 'sequel'
gem 'sqlite3'
gem 'fileutils', '~> 1.5'
gem 'down'
gem 'logger'
gem 'yard'
gem 'thread'
gem 'concurrent-ruby', require: 'concurrent'